# Generated by Django 4.2.5 on 2023-09-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_catagpry_member_catagory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='projects',
        ),
    ]
